#!/usr/bin/env python3
"""Aggregate the epoch sensitivity checks used by the paper.

The sensitivity table is a local coverage check around the epoch-level
`realistic_big` anchor. It reads `realistic_analysis_*.json` files generated by
`analyze_realistic.py` and reports online-vs-static deltas for:

- the baseline `realistic_big_{a..e}` repeated trials,
- slower/faster drift variants,
- lower/higher high-tier write-pressure variants.

The compact public artifact keeps the checked-in summary tables but omits the
large raw/analysis inputs. In that compact mode this script must fail before
writing misleading `n=0` output. Pass `--allow-missing` only when intentionally
producing a partial diagnostic table.
"""
from __future__ import annotations

import argparse
import glob
import json
import math
import statistics
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

T_CRIT_975 = {
    2: 12.706,
    3: 4.303,
    4: 3.182,
    5: 2.776,
    6: 2.571,
    7: 2.447,
    8: 2.365,
    9: 2.306,
    10: 2.262,
}

COMPARE_METRICS = [
    ("online_vs_static_pct_high_mean_write_p99_us", "High write P99"),
    ("online_vs_static_pct_high_sum_ops_per_sec", "High throughput"),
    ("online_vs_static_pct_sum_ops_per_sec", "Total throughput"),
    ("online_vs_static_pct_sum_compact_write_bytes", "Compact bytes"),
    ("online_vs_static_pct_mid_sum_ops_per_sec", "Mid throughput"),
]

PROMOTE_RULE = {
    "high_p99_max_pct": -2.0,
    "high_tput_min_pct": 5.0,
    "overlap_min": 2.5,
}
CAPACITY_BOUNDARY = {
    "stall_p99_ratio_vs_baseline": 2.0,
    "fallback_stall_p99_us": 500_000.0,
}
AXIS_PRIORITY = ["press", "drift"]


def default_variants(results_dir: Path) -> list[tuple[str, str]]:
    return [
        ("baseline", str(results_dir / "realistic_analysis_realistic_big_*.json")),
        ("drift_slow", str(results_dir / "realistic_analysis_sens_drift_slow_*.json")),
        ("drift_fast", str(results_dir / "realistic_analysis_sens_drift_fast_*.json")),
        ("press_low", str(results_dir / "realistic_analysis_sens_press_low_*.json")),
        ("press_high", str(results_dir / "realistic_analysis_sens_press_high_*.json")),
    ]


def summarize(values: list[float]) -> dict:
    n = len(values)
    if n == 0:
        return {"n": 0}
    out: dict[str, object] = {
        "n": n,
        "mean": statistics.fmean(values),
        "min": min(values),
        "max": max(values),
        "range": max(values) - min(values),
    }
    if n > 1:
        out["stdev"] = statistics.stdev(values)
        out["sem"] = out["stdev"] / math.sqrt(n)
    else:
        out["stdev"] = 0.0
        out["sem"] = 0.0
    if n >= 3 and n in T_CRIT_975:
        margin = T_CRIT_975[n] * out["sem"]
        out["ci95_low"] = out["mean"] - margin
        out["ci95_high"] = out["mean"] + margin
        out["ci95_margin"] = margin
    else:
        out["ci95_low"] = None
        out["ci95_high"] = None
        out["ci95_margin"] = None
    return out


def fmt_pct(stat: dict, precision: int = 1) -> str:
    if not stat or stat.get("n", 0) == 0:
        return "n/a"
    n = stat["n"]
    mean = stat["mean"]
    if n == 1:
        return f"{mean:+.{precision}f}% (n=1)"
    if n == 2:
        return f"{mean:+.{precision}f}% [{stat['min']:+.1f},{stat['max']:+.1f}]"
    if stat.get("ci95_margin") is not None:
        return f"{mean:+.{precision}f}% +/-{stat['ci95_margin']:.1f}"
    return f"{mean:+.{precision}f}% (n={n})"


def fmt_overlap(stat: dict) -> str:
    if not stat or stat.get("n", 0) == 0:
        return "n/a"
    return f"{stat['mean']:.2f}/4"


def recover_trial(path: Path) -> str:
    name = path.name
    return name.removeprefix("realistic_analysis_").removesuffix(".json")


def load_trial(path: Path) -> dict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    summary = payload["summary"]
    compare = {k: float(summary.get(k, 0.0)) for k, _ in COMPARE_METRICS}
    return {
        "path": str(path),
        "trial": recover_trial(path),
        "compare": compare,
        "overlap_after_warmup": float(summary.get("online_high_overlap_mean_after_warmup", 0.0)),
        "failed_static": float(summary.get("failed_tenants_static", 0.0)),
        "failed_online": float(summary.get("failed_tenants_online", 0.0)),
        "static_high_stall_p99_us": float(summary.get("static_high_stall_p99_us_mean", 0.0)),
        "static_total_stall_count": float(summary.get("static_total_stall_count_sum", 0.0)),
        "epochs_per_stage": summary.get("epochs_per_stage"),
        "writes_high": summary.get("writes_high"),
        "value_size": summary.get("value_size"),
        "epochs": summary.get("epochs"),
    }


def tier_rows(payload: dict, tier: str) -> list[dict]:
    return [r for r in payload.get("workload", []) if r.get("tier") == tier]


def baseline_static_high_stall_p99(paths: list[Path]) -> float | None:
    means: list[float] = []
    for analysis_path in paths:
        trial = recover_trial(analysis_path)
        raw_path = analysis_path.with_name(f"realistic_static_{trial}.json")
        if not raw_path.exists():
            continue
        try:
            payload = json.loads(raw_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        high_stalls = [
            float(r.get("stall_p99_us", 0.0))
            for r in tier_rows(payload, "high")
        ]
        if high_stalls:
            means.append(statistics.fmean(high_stalls))
    return statistics.fmean(means) if means else None


def classify_variant(stats: dict, indicators: dict, baseline_stall_p99: float | None) -> str:
    if indicators["max_failed_static"] > 0:
        return "capacity-boundary"
    if baseline_stall_p99 is not None and baseline_stall_p99 > 0:
        threshold = CAPACITY_BOUNDARY["stall_p99_ratio_vs_baseline"] * baseline_stall_p99
        if indicators["max_static_high_stall_p99"] > threshold:
            return "capacity-boundary"
    if stats["overlap"]["mean"] < PROMOTE_RULE["overlap_min"]:
        return "controller-boundary"

    high_p99 = stats["high_p99"]["mean"]
    high_tput = stats["high_tput"]["mean"]
    compact_bytes = stats["compact_bytes"]["mean"]
    if high_p99 <= PROMOTE_RULE["high_p99_max_pct"] and high_tput >= PROMOTE_RULE["high_tput_min_pct"]:
        return "promote"
    direction_hits = sum(
        [
            high_p99 <= PROMOTE_RULE["high_p99_max_pct"],
            high_tput >= PROMOTE_RULE["high_tput_min_pct"],
            compact_bytes <= -2.0,
        ]
    )
    if direction_hits >= 2:
        return "partial"
    return "no-promote"


def selection_target(variants: list[dict]) -> dict | None:
    eligible = [v for v in variants if v.get("verdict") == "promote"]
    if not eligible:
        return None

    def key(item: dict) -> tuple[int, str]:
        name = item["name"]
        axis = next((i for i, label in enumerate(AXIS_PRIORITY) if label in name), len(AXIS_PRIORITY))
        return axis, name

    return sorted(eligible, key=key)[0]


def parse_variants(raw_variants: list[str] | None, results_dir: Path) -> list[tuple[str, str]]:
    if not raw_variants:
        return default_variants(results_dir)
    parsed: list[tuple[str, str]] = []
    for item in raw_variants:
        if ":" not in item:
            print(f"malformed --variant '{item}', expected <name>:<glob>", file=sys.stderr)
            raise SystemExit(2)
        name, pattern = item.split(":", 1)
        parsed.append((name.strip(), pattern.strip()))
    return parsed


def summarize_variant(name: str, pattern: str, baseline_name: str, baseline_stall_p99: float | None) -> dict:
    paths = [Path(p) for p in sorted(glob.glob(pattern))]
    if not paths:
        return {"name": name, "pattern": pattern, "n": 0, "verdict": "no-data"}
    per_trial = [load_trial(path) for path in paths]
    stats = {
        "high_p99": summarize([t["compare"]["online_vs_static_pct_high_mean_write_p99_us"] for t in per_trial]),
        "high_tput": summarize([t["compare"]["online_vs_static_pct_high_sum_ops_per_sec"] for t in per_trial]),
        "total_tput": summarize([t["compare"]["online_vs_static_pct_sum_ops_per_sec"] for t in per_trial]),
        "compact_bytes": summarize([t["compare"]["online_vs_static_pct_sum_compact_write_bytes"] for t in per_trial]),
        "mid_tput": summarize([t["compare"]["online_vs_static_pct_mid_sum_ops_per_sec"] for t in per_trial]),
        "overlap": summarize([t["overlap_after_warmup"] for t in per_trial]),
    }
    indicators = {
        "max_failed_static": max((t["failed_static"] for t in per_trial), default=0.0),
        "max_failed_online": max((t["failed_online"] for t in per_trial), default=0.0),
        "max_static_high_stall_p99": max((t["static_high_stall_p99_us"] for t in per_trial), default=0.0),
        "max_static_total_stall_count": max((t["static_total_stall_count"] for t in per_trial), default=0.0),
    }
    verdict = "baseline" if name == baseline_name else classify_variant(stats, indicators, baseline_stall_p99)
    return {
        "name": name,
        "pattern": pattern,
        "n": len(per_trial),
        "stats": stats,
        "indicators": indicators,
        "trials": per_trial,
        "verdict": verdict,
    }


def render_markdown(payload: dict, autotuned_pick: dict | None) -> str:
    lines: list[str] = [
        "# Sensitivity-Checks Aggregate",
        "",
        "Four-point local screening around the `realistic_big` main",
        "configuration (drift slow/fast, pressure low/high). Value-size",
        "sensitivity is deferred and only appears if its result files exist.",
        "These checks are not a full workload survey; they test whether the",
        "main effect survives local perturbations around the main configuration.",
        "The faster-drift point is used to expose the controller boundary,",
        "not as a failure case to hide. The fast-drift variant stresses",
        "early adaptation and then measures recovery once the high set reaches",
        "its terminal stage; it is not a pure 'high drift frequency' setting.",
        "",
        "| variant | n | high P99 | high tput | total tput | compact bytes | mid tput | overlap | static stall p99 (us, max) | failed | verdict |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|:--|",
    ]
    for variant in payload["variants"]:
        if variant.get("n", 0) == 0:
            lines.append(f"| {variant['name']} | 0 | n/a | n/a | n/a | n/a | n/a | n/a | n/a | n/a | no-data |")
            continue
        stats = variant["stats"]
        indicators = variant["indicators"]
        lines.append(
            f"| {variant['name']} | {variant['n']} | "
            f"{fmt_pct(stats['high_p99'])} | "
            f"{fmt_pct(stats['high_tput'])} | "
            f"{fmt_pct(stats['total_tput'])} | "
            f"{fmt_pct(stats['compact_bytes'])} | "
            f"{fmt_pct(stats['mid_tput'])} | "
            f"{fmt_overlap(stats['overlap'])} | "
            f"{indicators['max_static_high_stall_p99']:.0f} | "
            f"{int(indicators['max_failed_static'])}/{int(indicators['max_failed_online'])} | "
            f"{variant['verdict']} |"
        )

    lines.extend(
        [
            "",
            "Rendering rules (pre-committed; no post-hoc selection):",
            "- n=2 cells show `mean [min, max]`; no CI/stdev is rendered. Direction",
            "  is the only claim supported by two screening trials.",
            "- n>=3 cells show `mean +/-CI` (Student-t 95% half-width).",
            "- The verdict column is an *engineering* filter that decides which",
            "  variants merit promotion to a five-trial run with confidence",
            "  intervals. It is not a statistical acceptance test.",
            "",
            "Verdict labels:",
            "- `promote`: high P99 <= -2% AND high tput >= +5% AND overlap >= 2.5/4 AND not capacity-boundary.",
            "- `partial`: direction correct on >=2 of {high P99, high tput, compact bytes} but borderline.",
            "- `controller-boundary`: high-set overlap < 2.5/4. Controller could not track the high set at this drift speed; reported honestly, not hidden.",
            "- `capacity-boundary`: static failed tenants > 0 OR static-high stall P99 > 2x baseline static-high stall P99. Reported as a capacity/saturation observation, not as evidence of controller regression.",
            "- `no-promote`: none of the headline metrics moves in the expected direction.",
            "",
        ]
    )
    baseline_stall = payload.get("baseline_static_high_stall_p99_us")
    if baseline_stall is not None:
        threshold = CAPACITY_BOUNDARY["stall_p99_ratio_vs_baseline"] * baseline_stall
        lines.append(
            "Baseline static-high stall P99 mean (across realistic_big_a..e): "
            f"{baseline_stall:.0f} us. Capacity-boundary threshold: {threshold:.0f} us (2x baseline)."
        )
    else:
        lines.append(
            "Baseline static-high stall P99 unavailable. Capacity boundary is "
            "flagged only on static failures until raw static baseline runs are restored."
        )
    lines.extend(
        [
            "",
            "Promotion-target selection for `static_autotuned` (pre-committed):",
            "- Eligible set: variants with verdict `promote`.",
            "- Sort key: axis priority (pressure before drift), then lexicographic",
            "  variant name. This rule does NOT depend on observed effect size.",
        ]
    )
    if autotuned_pick:
        lines.append(f"- **Selected target for static_autotuned**: `{autotuned_pick['name']}`.")
    else:
        lines.append("- **No eligible variant yet** (none currently `promote`).")
    lines.extend(
        [
            "",
            "Wording for the paper:",
            "> These checks are not a full workload survey; they test whether the",
            "> main effect survives local perturbations around the main",
            "> configuration. The faster-drift point is used to expose the",
            "> controller boundary, not as a failure case to hide.",
        ]
    )
    return "\n".join(lines) + "\n"


def fail_if_missing(variants: list[dict], allow_missing: bool) -> None:
    missing = [v for v in variants if v.get("n", 0) == 0]
    if allow_missing or not missing:
        return
    print(
        "Refusing to write sensitivity aggregate: requested raw analysis files are missing.",
        file=sys.stderr,
    )
    print(
        "Restore the full results directory, or pass --allow-missing for an explicit partial diagnostic.",
        file=sys.stderr,
    )
    for variant in missing:
        print(f"  missing variant {variant['name']}: {variant['pattern']}", file=sys.stderr)
    raise SystemExit(2)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--results-dir",
        type=Path,
        default=ROOT / "remote-results",
        help="Directory holding realistic_analysis_*.json files.",
    )
    parser.add_argument(
        "--variant",
        action="append",
        help="Variant as <name>:<glob>. Defaults to the paper sensitivity variants.",
    )
    parser.add_argument("--baseline-variant-name", default="baseline")
    parser.add_argument("--out-markdown", type=Path)
    parser.add_argument("--out-json", type=Path)
    parser.add_argument(
        "--allow-missing",
        action="store_true",
        help="Allow a diagnostic no-data table instead of failing when requested variants have no raw analysis files.",
    )
    args = parser.parse_args()

    variants = parse_variants(args.variant, args.results_dir)
    baseline_pattern = next((pattern for name, pattern in variants if name == args.baseline_variant_name), "")
    baseline_paths = [Path(p) for p in sorted(glob.glob(baseline_pattern))] if baseline_pattern else []
    baseline_stall = baseline_static_high_stall_p99(baseline_paths) if baseline_paths else None

    payload: dict[str, object] = {
        "variants": [
            summarize_variant(name, pattern, args.baseline_variant_name, baseline_stall)
            for name, pattern in variants
        ],
        "baseline_static_high_stall_p99_us": baseline_stall,
        "promote_rule": PROMOTE_RULE,
        "capacity_boundary_rule": CAPACITY_BOUNDARY,
    }
    fail_if_missing(payload["variants"], args.allow_missing)

    autotuned_pick = selection_target(payload["variants"])
    payload["autotuned_promotion_target"] = autotuned_pick["name"] if autotuned_pick else None
    markdown = render_markdown(payload, autotuned_pick)

    if args.out_markdown:
        args.out_markdown.parent.mkdir(parents=True, exist_ok=True)
        args.out_markdown.write_text(markdown, encoding="utf-8")
    if args.out_json:
        args.out_json.parent.mkdir(parents=True, exist_ok=True)
        args.out_json.write_text(json.dumps(payload, indent=2, sort_keys=True, default=str), encoding="utf-8")
    print(markdown)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
